In [13]:
import numpy as np
import math

In [14]:
from Coursework.PSO import pswarm as ps
from Coursework.PSO import psobehaviour as psh
from Coursework.PSO.history import PSOHistory as annh
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
class TrivialOptimisation:
    def __init__(self, best_position = [0.45, -0.1], search_dimension=[(-1.0, 1.0),(-1.0, 1.0)], num_particles=10, num_iterations=100):
        self.best_position = np.array(best_position)
        self.search_dimension = search_dimension
        self.all_vectors = []
        self.num_particles = num_particles
        self.num_iterations = num_iterations

    def evaluate_fitness(self, vec):
        return 1 / (self.vec_distance(vec) + 0.0000001)

    def vec_distance(self, vec):
        return math.sqrt(np.sum((self.best_position - vec)**2))
    

In [16]:
pos = [0.45, -0.1, 0.5, 0.45, -0.1, 0.5]
dim = [(-1.0, 1.0), (-1.0, 1.0), (-1, 1.0),(-1.0, 1.0), (-1.0, 1.0), (-1, 1.0)]
triv = TrivialOptimisation(pos, search_dimension=dim)
triv_h = annh(triv)

In [17]:
pso = ps.PSO(swarm_size=10, num_informants=2, boundary_policy=psh.BoundaryPolicy.RANDOMREINIT, termination_policy=[psh.TerminationPolicy.ITERATIONS], termination_args={'max_iter': 400}, alpha=0.61, beta=0.4, gamma=0.4, delta=0.4, epsilon=0.61)

pso.set_search_dimensions(triv.search_dimension)
pso.set_fitness_fn(triv_h.evaluate_fitness)
best = pso.run()

Fitness: 6.620954939605043:   0%|          | 0.0/100 [00:01<?, ?it/s]


In [18]:
pso.best.fitness

6.620954939605043

In [19]:
triv_h.historical_particle_fitness()
triv_h.historical_particle_location()

7854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.42709431, -0.18429465,  0.4834069 ,  0.56887296, -0.1180279 ,
          0.47877854]),
  array([ 0.

In [20]:
triv_h.best_iter_per_particle()

[235, 237, 234, 233, 236, 235, 236, 234, 244, 239]