In [3]:
from SamModel import model as mod
%load_ext autoreload
%autoreload 2


In [4]:
input_mat = mod.weight_matrix(10000,2)
result_mat = mod.weight_matrix(10000, 1)

In [13]:
model = mod.ANN()
model.set_input(input_mat, result_mat)
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="relu"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(1, activation="sigmoid"))
#print(len(model.layers))
model.compile()

# model.epoch(input_mat)
#model.weights[0].shape[1]
#model.bias[0].shape[0] == 

Model Compiled!


In [15]:
model.one_pass()

yhat = model.layers[-1].output

In [16]:

import numpy as np
print(np.mean((result_mat - yhat)**2))

print(mod.apply_loss(result_mat, yhat))

1.3305635252629495
1.3305635252629495


In [18]:
np.unique(model.y_hat)

array([0.99999999, 0.99999999, 0.99999999, ..., 1.        , 1.        ,
       1.        ])

In [23]:

vec_a = 2*np.random.rand(5)-1
vec_b = 2*np.random.rand(5)-1
print("a", vec_a)
print("b", vec_b)

a [-0.15993532  0.70374582 -0.89854746 -0.11118929 -0.13303417]
b [ 0.9496636  -0.58536648 -0.91996408 -0.74872937 -0.91167048]


In [24]:
out = vec_a + vec_b
out.shape[0]

5

In [25]:
mat = np.array([[0.5, 0.5, 0.5], [0.5,0.5, 0.5]])
vec = np.array([1.0, 2.0, 3.0])
mat

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [26]:
mat + vec

array([[1.5, 2.5, 3.5],
       [1.5, 2.5, 3.5]])