In [33]:
import model as mod
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
input_mat = mod.__weight_matrix__(3,2)
result_mat = mod.__weight_matrix__(3, 1)

In [35]:
model = mod.ANN()
model.set_input_cols(2)
model.add(mod.Layer(5, activation="sigmoid"))
model.add(mod.Layer(3, activation="sigmoid"))
#print(len(model.layers))
model.compile()

# model.epoch(input_mat)
#model.weights[0].shape[1]
#model.bias[0].shape[0] == 

Model Compiled!


In [36]:
model.epoch(input_mat)

model.layer_outputs

[array([[0.43365092, 0.5357357 , 0.31383579, 0.19852324, 0.43280151],
        [0.41614783, 0.69027552, 0.46683486, 0.34448454, 0.62568995],
        [0.44261471, 0.70512606, 0.433336  , 0.27865472, 0.60572196]]),
 array([[0.27018049, 0.68646667, 0.6992465 ],
        [0.26072649, 0.69559983, 0.70118053],
        [0.25375325, 0.69236741, 0.69387846]])]

In [7]:
import numpy as np

vec_a = 2*np.random.rand(5)-1
vec_b = 2*np.random.rand(5)-1
print("a", vec_a)
print("b", vec_b)

a [-0.2079169  -0.46756626  0.26532028 -0.42937715  0.63713061]
b [-0.83907075 -0.05055559  0.24130667  0.65674205  0.1340894 ]


In [10]:
out = vec_a + vec_b
out.shape[0]

5

In [11]:
mat = np.array([[0.5, 0.5, 0.5], [0.5,0.5, 0.5]])
vec = np.array([1.0, 2.0, 3.0])
mat

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [12]:
mat + vec

array([[1.5, 2.5, 3.5],
       [1.5, 2.5, 3.5]])