In [1]:
import model as mod
%load_ext autoreload
%autoreload 2


In [37]:
input_mat = mod.__weight_matrix__(100000,2)
result_mat = mod.__weight_matrix__(100000, 1)

In [38]:
model = mod.ANN()
model.set_input(input_mat, result_mat)
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(512, activation="sigmoid"))
model.add(mod.Layer(1, activation="sigmoid"))
#print(len(model.layers))
model.compile()

# model.epoch(input_mat)
#model.weights[0].shape[1]
#model.bias[0].shape[0] == 

Model Compiled!


In [39]:
model.one_pass()

model.layers[-1].output

array([[0.01871245],
       [0.01041449],
       [0.02910432],
       ...,
       [0.07712665],
       [0.05239077],
       [0.00270107]])

In [7]:
import numpy as np

vec_a = 2*np.random.rand(5)-1
vec_b = 2*np.random.rand(5)-1
print("a", vec_a)
print("b", vec_b)

a [-0.2079169  -0.46756626  0.26532028 -0.42937715  0.63713061]
b [-0.83907075 -0.05055559  0.24130667  0.65674205  0.1340894 ]


In [10]:
out = vec_a + vec_b
out.shape[0]

5

In [11]:
mat = np.array([[0.5, 0.5, 0.5], [0.5,0.5, 0.5]])
vec = np.array([1.0, 2.0, 3.0])
mat

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [12]:
mat + vec

array([[1.5, 2.5, 3.5],
       [1.5, 2.5, 3.5]])