In [1]:
from datetime import datetime, timedelta

In [2]:
from ANNModel import model as mod
from PSO import pswarm as ps
from PSO import psobehaviour as psh
%load_ext autoreload
%autoreload 2

import numpy as np
from ANNModel import data as d

In [3]:
data = d.Data("./Data/1in_linear.txt")
input_mat = data.get_rows()
result_mat = data.get_output()

In [4]:
model = mod.ANN()
model.set_training_input(input_mat, result_mat)
model.add(mod.Layer(2, activation="gaussian"))
model.add(mod.Layer(8, activation='relu'))
model.add(mod.Layer(1, activation="sigmoid"))
model.compile()



Model Compiled!


In [5]:
model.one_pass()

In [6]:
random_model = model.vectorize()

In [ ]:
import copy
model_copy = copy.deepcopy(model)

In [7]:
pso = ps.PSO(swarm_size=10, num_informants=2, boundary_policy=psh.BoundaryPolicy.RANDOMREINIT, termination_policy=[psh.TerminationPolicy.ITERATIONS], termination_args={'max_iter': 50})

In [8]:
pso.set_search_dimensions(model.dimension_vec())
pso.set_fitness_fn(model.assess_fitness)

<bound method ANN.assess_fitness of <ANNModel.model.ANN object at 0x0000029A7C4FCCD0>>


In [9]:
model.assess_fitness

<bound method ANN.assess_fitness of <ANNModel.model.ANN object at 0x0000029A7C4FCCD0>>

In [10]:
pso.run()

Iteration:  0
Fitness:  2.999400119976005
Iteration:  1
Fitness:  2.999400119976005
Iteration:  2
Fitness:  2.999400119976005
Iteration:  3
Fitness:  2.999400119976005
Iteration:  4
Fitness:  2.999400119976005
Iteration:  5
Fitness:  2.999400119976005
Iteration:  6
Fitness:  2.999400119976005
Iteration:  7
Fitness:  2.999400119976005
Iteration:  8
Fitness:  2.999400119976005
Iteration:  9
Fitness:  2.999400119976005
Iteration:  10
Fitness:  2.999400119976005
Iteration:  11
Fitness:  2.999400119976005
Iteration:  12
Fitness:  2.999400119976005
Iteration:  13
Fitness:  2.999400119976005
Iteration:  14
Fitness:  2.999400119976005
Iteration:  15
Fitness:  2.999400119976005
Iteration:  16
Fitness:  2.999400119976005
Iteration:  17
Fitness:  2.999400119976005
Iteration:  18
Fitness:  2.999400119976005
Iteration:  19
Fitness:  2.999400119976005
Iteration:  20
Fitness:  2.999400119976005
Iteration:  21
Fitness:  2.999400119976005
Iteration:  22
Fitness:  2.999400119976005
Iteration:  23
Fitnes

In [11]:
PSO_best = pso.best.location
PSO_fitness = pso.best.fitness

In [ ]:
model.assess_fitness(random_model)

In [12]:
print(pso.fitness_fn)

<bound method ANN.assess_fitness of <ANNModel.model.ANN object at 0x0000029A7C4FCCD0>>


In [13]:
old = PSO_best
PSO_best[0] = 4

1.1726677222378066

In [15]:
print('Model fitness: ', model.assess_fitness(PSO_best))


Model fitness:  0.7613392930745075


In [16]:
model.vectorize()

array([ 4.00000000e+00,  2.04308744e-01, -3.91867162e-01,  1.19936086e-02,
       -1.83666403e-01,  3.00000000e+00, -5.07430453e-02, -1.49700351e-01,
       -3.55530452e-01, -5.00352186e-01,  2.69187072e-01,  3.21388437e-02,
        1.32121591e-02,  4.76079968e-01,  4.55975951e-01, -2.94534280e-01,
       -5.70699042e-01, -1.54544605e-01,  2.08395304e-01,  3.11431762e-03,
        4.07807013e-02,  1.76944692e-01, -6.04857967e-01, -4.22587532e-01,
       -2.51443670e-02, -3.70599874e-01, -3.48560506e-01,  3.67594944e-01,
        4.54196469e-01, -2.73657850e-02,  3.00000000e+00,  3.62458925e-01,
       -2.88474435e-01, -7.14508162e-02,  5.84821141e-01,  7.78613787e-03,
        3.48157196e-01, -6.18314813e-01, -1.55183849e-01,  1.94321403e-01])

In [17]:
PSO_best

array([ 4.00000000e+00,  2.04308744e-01, -3.91867162e-01,  1.19936086e-02,
       -1.83666403e-01,  2.77299957e+00, -5.07430453e-02, -1.49700351e-01,
       -3.55530452e-01, -5.00352186e-01,  2.69187072e-01,  3.21388437e-02,
        1.32121591e-02,  4.76079968e-01,  4.55975951e-01, -2.94534280e-01,
       -5.70699042e-01, -1.54544605e-01,  2.08395304e-01,  3.11431762e-03,
        4.07807013e-02,  1.76944692e-01, -6.04857967e-01, -4.22587532e-01,
       -2.51443670e-02, -3.70599874e-01, -3.48560506e-01,  3.67594944e-01,
        4.54196469e-01, -2.73657850e-02,  3.42866815e+00,  3.62458925e-01,
       -2.88474435e-01, -7.14508162e-02,  5.84821141e-01,  7.78613787e-03,
        3.48157196e-01, -6.18314813e-01, -1.55183849e-01,  1.94321403e-01])

In [18]:
print('old fitness: ', model.assess_fitness(old))

old fitness:  0.7613392930745075


In [19]:
model.vectorize()

array([ 4.00000000e+00,  2.04308744e-01, -3.91867162e-01,  1.19936086e-02,
       -1.83666403e-01,  3.00000000e+00, -5.07430453e-02, -1.49700351e-01,
       -3.55530452e-01, -5.00352186e-01,  2.69187072e-01,  3.21388437e-02,
        1.32121591e-02,  4.76079968e-01,  4.55975951e-01, -2.94534280e-01,
       -5.70699042e-01, -1.54544605e-01,  2.08395304e-01,  3.11431762e-03,
        4.07807013e-02,  1.76944692e-01, -6.04857967e-01, -4.22587532e-01,
       -2.51443670e-02, -3.70599874e-01, -3.48560506e-01,  3.67594944e-01,
        4.54196469e-01, -2.73657850e-02,  3.00000000e+00,  3.62458925e-01,
       -2.88474435e-01, -7.14508162e-02,  5.84821141e-01,  7.78613787e-03,
        3.48157196e-01, -6.18314813e-01, -1.55183849e-01,  1.94321403e-01])