In [1]:
from SamModel import model as mod
from PSO import pswarm as ps
%load_ext autoreload
%autoreload 2



In [2]:
input_mat = mod.weight_matrix(5,2)
result_mat = mod.weight_matrix(5, 1)

In [4]:
model = mod.ANN()
model.set_training_input(input_mat, result_mat)
model.add(mod.Layer(10, activation="relu"))
model.add(mod.Layer(5, activation="sigmoid"))
model.add(mod.Layer(2, activation="sigmoid"))
model.add(mod.Layer(1, activation="sigmoid"))
#print(len(model.layers))
model.compile()

# model.epoch(input_mat)
#model.weights[0].shape[1]
#model.bias[0].shape[0] == 

Model Compiled!


In [5]:
model.layers[0].weights

array([[-0.76192343,  0.2538412 , -0.44632548, -0.41944767,  0.52373189,
        -0.01183606,  0.09527752, -0.09956545,  0.77004686,  0.70922987],
       [ 0.47965782, -0.11161683, -0.77203602, -0.75376111, -0.68227298,
         0.31334889, -0.42529576, -0.57897262, -0.55523741, -0.77788126]])

In [6]:
input_mat.dot(model.layers[0].weights).shape

(5, 10)

In [25]:
model.layers[0].to_vec()

array([-0.76192343,  0.2538412 , -0.44632548, -0.41944767,  0.52373189,
       -0.01183606,  0.09527752, -0.09956545,  0.77004686,  0.70922987,
        0.47965782, -0.11161683, -0.77203602, -0.75376111, -0.68227298,
        0.31334889, -0.42529576, -0.57897262, -0.55523741, -0.77788126,
        0.74997693,  0.82670883, -0.55171562, -0.18317202, -0.43897954,
       -0.41029248,  0.92702305, -0.8317038 , -0.63636302,  0.67725761,
        5.        ])

In [36]:
int(mod.ActivationFunction.SIGMOID)

1

In [24]:
import numpy as np
y = np.append(model.layers[0].weights.flatten(), model.layers[0].bias.flatten(), int(model.layers[0].activation), axis=0)
y

TypeError: _append_dispatcher() got multiple values for argument 'axis'

In [21]:
 t = np.array([])

array([-0.76192343,  0.2538412 , -0.44632548, -0.41944767,  0.52373189,
       -0.01183606,  0.09527752, -0.09956545,  0.77004686,  0.70922987,
        0.47965782, -0.11161683, -0.77203602, -0.75376111, -0.68227298,
        0.31334889, -0.42529576, -0.57897262, -0.55523741, -0.77788126,
        0.74997693,  0.82670883, -0.55171562, -0.18317202, -0.43897954,
       -0.41029248,  0.92702305, -0.8317038 , -0.63636302,  0.67725761,
        5.        ])

In [45]:
class Test:
    def __init__(self, p):
        self.a = 0
        self.b = 'asd'
        self.p = p

def add_one(t):
    print(t)
    print('before: ', t.p)
    t.p += 1
    print('after: ', t.p)
    return t

test = np.array([Test(1), Test(2), Test(3)])

test = list(map(add_one, test))
print(test[0].p)
print(test[1].p)
print(test[2].p)

print(test)

before:  1
after:  2
before:  2
after:  3
before:  3
after:  4
2
3
4
[<__main__.Test object at 0x000001C8CB18B760>, <__main__.Test object at 0x000001C8CB18B520>, <__main__.Test object at 0x000001C8CB18BEB0>]


In [5]:
import enum
TerminationPolicy = enum.Enum('TerminationPolicy', 'ITERATIONS DURATION CONVERGENCE')

test = [TerminationPolicy.ITERATIONS]

if TerminationPolicy.ITERATIONS in test:
    print(True)

True


In [23]:
import numpy as np
2*np.random.rand(3, 2)-1

array([[-0.30390511,  0.67909444],
       [ 0.70915121, -0.0463664 ],
       [-0.4982397 , -0.68136778]])

In [6]:

import numpy as np
print(np.mean((result_mat - yhat)**2))

print(mod.apply_loss(result_mat, yhat))

1.3019591390901992
1.3019591390901992


In [18]:
np.unique(model.y_hat)

array([0.99999999, 0.99999999, 0.99999999, ..., 1.        , 1.        ,
       1.        ])

In [23]:

vec_a = 2*np.random.rand(5)-1
vec_b = 2*np.random.rand(5)-1
print("a", vec_a)
print("b", vec_b)

a [-0.15993532  0.70374582 -0.89854746 -0.11118929 -0.13303417]
b [ 0.9496636  -0.58536648 -0.91996408 -0.74872937 -0.91167048]


In [24]:
out = vec_a + vec_b
out.shape[0]

5

In [25]:
mat = np.array([[0.5, 0.5, 0.5], [0.5,0.5, 0.5]])
vec = np.array([1.0, 2.0, 3.0])
mat

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [26]:
mat + vec

array([[1.5, 2.5, 3.5],
       [1.5, 2.5, 3.5]])